server:
   port: 8085
   
spring:
   datasource:
      url: jdbc:postgresql://127.0.0.1:5432/allendb
      name: allendb
      username: allen
      password: allen
      initialization-mode: never
      
   jpa:
      properties:
         hibernate:
            jdbc:
               lob:
                  non_contextual_creation: true
         org:
            hibernate:
               envers:
                  audit_table_suffix: _H
                  revision_field_name: AUDIT_REVISION
                  revision_type_field_name: ACTION_TYPE
                  store_data_at_delete: true
   liquibase:
      change-log: classpath:/db/changelog/changelog-master.xml                         
logging:
     level:
        root: WARN        
        org:
           springframework:
              security: WARN
              web:    
                 servlet: DEBUG      